-- ─────────────────────────────────────────────────────────────
-- MaPyramide — Seed domains + challenges
-- ─────────────────────────────────────────────────────────────

-- ─── Domaines ─────────────────────────────────────────────────
insert into public.domains (slug, label, color, bg_color, border_color, icon, tagline, stat_quote, order_index) values
  ('sante',           'Santé & Corps',       '#2E7D0E', '#EEF7E6', '#AAD8A0', '💪', 'Ton corps est ton premier investissement.',          'Moins de 5 000 pas/jour = sédentarité clinique (OMS)', 1),
  ('finances',        'Finances',            '#B87A10', '#FFF8EC', '#F5D48A', '💰', 'La liberté financière commence par la clarté.',      '48 % des Millennials ne se sentent pas en sécurité financièrement', 2),
  ('travail',         'Travail & Carrière',  '#1A5FA8', '#EEF4FF', '#A8C8F5', '💼', 'Travaille sur ce qui t''anime, pas ce qui t''épuise.', '90 % des Millennials veulent du sens au travail — 30 % l''ont trouvé', 3),
  ('entrepreneuriat', 'Entrepreneuriat',     '#B84020', '#FFF2EE', '#F5B8A8', '🚀', 'L''action bat le business plan.',                     '3 Français sur 10 veulent entreprendre — peu passent à l''acte', 4),
  ('bienetre',        'Bien-être',           '#5E4DC4', '#F3F1FF', '#C4BEF5', '🧠', 'Prends soin de ton mental autant que de ton corps.',  '35 % des Millennials se déclarent stressés en permanence', 5),
  ('ecologie',        'Écologie',            '#0E7A58', '#EAFAF4', '#8ADAC4', '🌱', 'Chaque geste compte — commence par un.',             '6 Millennials sur 10 sont anxieux face au climat sans savoir par où commencer', 6);

-- ─── Helper : récupérer l''id d''un domaine par slug ────────────
-- (utilisé dans les inserts ci-dessous via sous-requêtes)

-- ─── SANTÉ — 22 défis ─────────────────────────────────────────

-- Niveau 0 — La prise de conscience
insert into public.challenges (domain_id, level_index, order_index, title, duration, type, question, science_text, insight_text, metric_key, metric_label, metric_sub, is_measure) values
((select id from public.domains where slug='sante'), 0, 0,
  'Combien de pas fais-tu par jour, vraiment ?', '1 min', 'Mesure baseline',
  'Ouvre l''application Santé de ton téléphone (ou Google Fit). Note ta moyenne exacte de pas sur les 7 derniers jours. Ce chiffre est ton point zéro — il est parfait, quel qu''il soit.',
  'La sédentarité tue plus silencieusement que le tabac. Moins de 5 000 pas/jour = "sédentarité clinique" selon l''OMS. Mais la bonne nouvelle : passer de 4 000 à 7 000 pas réduit la mortalité de 50 % (JAMA Internal Medicine, 2021).',
  'Ta moyenne de pas sur 7 jours — le point zéro de ton parcours.',
  'pas', 'Tes pas / jour', 'Moyenne des 7 derniers jours dans ton appli Santé', true),

((select id from public.domains where slug='sante'), 0, 1,
  'Combien de litres d''eau bois-tu par jour en réalité ?', '2 min', 'Mesure baseline',
  'Pas l''idéal — la réalité. Pense à ta journée d''hier. Compte chaque verre, chaque bouteille. Café et thé comptent à 50 %. Sois honnête avec toi-même.',
  '75 % des Français sont en état de déshydratation chronique légère sans s''en rendre compte. Résultat : fatigue, maux de tête, fringales (le cerveau confond soif et faim), baisse de concentration de 20 %.',
  'Ton hydratation réelle — souvent bien en dessous de ce qu''on pense.',
  'hydra', 'Ton hydratation réelle', 'Litres d''eau bus hier (en honnêteté totale)', true),

((select id from public.domains where slug='sante'), 0, 2,
  'Combien de repas équilibrés cette semaine — compte-les', '2 min', 'Mesure baseline',
  'Un repas équilibré selon Flavio Guionneau : ½ assiette de légumes, ¼ protéines, ¼ glucides complexes. Regarde ta semaine passée. Combien de tes repas ressemblaient à ça ?',
  'Pas de régime. Pas d''aliment interdit. Flavio Guionneau répète : "Tu n''as pas à manger parfaitement — tu dois manger mieux que la semaine d''avant." 1 repas équilibré de plus par semaine change la trajectoire.',
  'Ton point de départ alimentaire — sans jugement, juste les chiffres.',
  'repas', 'Repas équilibrés cette semaine', 'Sur les 14 repas de ta semaine', true),

((select id from public.domains where slug='sante'), 0, 3,
  'Estime ton taux de masse grasse — méthode simple', '5 min', 'Mesure baseline',
  'Méthode tour de taille : mesure ton tour de taille (en cm) et ta taille (en cm). Ton ratio tour de taille/taille doit être < 0,5. Alternatively, utilise une balance à impédance ou les photos de référence visuelles en ligne (cherche "body fat percentage visual guide").',
  'Le taux de masse grasse est plus prédictif de la santé que le poids seul. L''IMC est imparfait — deux personnes au même IMC peuvent avoir des compositions corporelles radicalement différentes.',
  'Une estimation honnête, pas un verdict.',
  'masse', 'Taux de masse grasse estimé', 'Auto-évaluation — photos de référence ou balance à impédance', true);

-- Niveau 1 — Les fondations
insert into public.challenges (domain_id, level_index, order_index, title, duration, type, question, science_text, insight_text, metric_key, metric_label, metric_sub, is_measure) values
((select id from public.domains where slug='sante'), 1, 0,
  '10 minutes de marche — maintenant, pas ce soir', '10 min', 'Action immédiate',
  'Lève-toi maintenant. Pas besoin de tenue, de montre, ni de musique. Marche 10 minutes à l''extérieur. Reviens noter tes pas pendant cette marche.',
  'Tibo InShape le dit souvent : "Le meilleur entraînement, c''est celui que tu fais." Une étude Stanford (2014) confirme : 10 minutes de marche améliorent l''humeur pendant 2 heures et réduisent les pensées négatives de 12 %.',
  'Le premier pas — littéralement.',
  'pas', 'Tes pas pendant ces 10 minutes', 'Rien qu''avec cette marche', true),

((select id from public.domains where slug='sante'), 1, 1,
  'La bouteille visible — ton système d''hydratation', '3 min', 'System design',
  'Prends une bouteille de 1,5 L. Remplis-la. Pose-la à côté de toi pour toute la journée. Règle simple : elle doit être vide ce soir. Note combien tu as bu au total.',
  'James Clear (Atomic Habits) l''a prouvé : rendre un comportement visible multiplie sa fréquence. "On ne boit pas par discipline — on boit quand c''est sous les yeux." Une bouteille visible double l''hydratation quotidienne sans effort de volonté.',
  'L''environnement détermine le comportement.',
  'hydra', 'Litres bus aujourd''hui', 'Avec la bouteille visible toute la journée', true),

((select id from public.domains where slug='sante'), 1, 2,
  'Construis ton assiette équilibrée ce soir', '20 min', 'Action cuisine',
  'Ce soir au dîner : ½ assiette de légumes (cuits ou crus), ¼ de protéines (viande, poisson, œufs, légumineuses), ¼ de glucides complexes (riz, pâtes, patate douce). Prends une photo. Note combien de temps ça t''a pris.',
  'Flavio Guionneau insiste : "Le rééquilibrage alimentaire ne se fait pas en supprimant — il se fait en ajoutant." Les fibres ralentissent l''absorption des glucides, prolongent la satiété et nourrissent le microbiote.',
  'Un repas, une assiette, une habitude qui change tout.',
  'repas', 'Repas équilibrés cette semaine', 'Compte ce repas + tous ceux de la semaine', true),

((select id from public.domains where slug='sante'), 1, 3,
  'Ta première séance de sport — 20 minutes, corps au sol', '20 min', '1ère séance',
  'Pas de salle, pas d''équipement. 5 squats, 5 pompes (genoux si besoin), 20 secondes de gainage. Répète 3 fois. Repose. C''est tout. Note combien de séries tu as faites.',
  'Tibo InShape : "Tout le monde peut faire 20 minutes. Le problème n''est pas la capacité — c''est la décision de commencer." La science confirme : les 5 premières séances créent les connexions neuromusculaires qui rendent les suivantes 3× plus faciles.',
  'La douleur musculaire des premiers jours est la preuve que ça marche.',
  'seances', 'Séances sport cette semaine', 'Cette séance compte — même la plus petite', true),

((select id from public.domains where slug='sante'), 1, 4,
  'Note tes pas 7 jours de suite — juste observer', '30 sec/j × 7', 'Tracking',
  'Pendant 7 jours, note tes pas chaque soir. Pas d''objectif encore. Juste la mesure. Rentre la moyenne des 7 jours à la fin.',
  'Les porteurs de podomètre font en moyenne +1 400 pas/jour de plus simplement grâce à la prise de conscience — sans aucune instruction supplémentaire. C''est l''effet Hawthorne.',
  'Être observé, même par soi-même, change le comportement.',
  'pas', 'Moyenne tes pas sur 7 jours', 'Ta nouvelle moyenne après 1 semaine de conscience', true);

-- Niveau 2 — La régularité : 21 jours
insert into public.challenges (domain_id, level_index, order_index, title, duration, type, question, science_text, insight_text, metric_key, metric_label, metric_sub, is_measure) values
((select id from public.domains where slug='sante'), 2, 0,
  'Programme 3 séances dans ton calendrier — cette semaine', '3 min', 'Planification',
  'Ouvre ton agenda. Bloque 3 créneaux de 30 minutes minimum pour du sport cette semaine. Durée, type, lieu. Ces créneaux sont des rendez-vous avec toi-même — aussi importants qu''une réunion pro.',
  'Les séances planifiées ont 3× plus de chances d''être tenues que les séances improvisées (American Journal of Preventive Medicine). Tibo InShape : "Si ce n''est pas dans ton agenda, ça n''existe pas."',
  'La planification est le vrai muscle à entraîner.',
  'seances', 'Séances tenues cette semaine', 'Pas prévues — réellement faites', true),

((select id from public.domains where slug='sante'), 2, 1,
  'La règle des 2 jours — ne jamais sauter deux fois de suite', '2 min', 'Règle système',
  'La règle d''or de Tibo InShape : tu peux sauter 1 séance. Jamais 2 d''affilée. Réfléchis à ta semaine passée. As-tu sauté 2 séances consécutives ? Si oui, qu''est-ce qui s''est passé ? Si non, félicite-toi.',
  'James Clear (Atomic Habits) : "Ne jamais rater deux fois est la règle n°1." Rater une fois est un accident. Rater deux fois, c''est le début d''une nouvelle habitude — la mauvaise.',
  'La régularité bat toujours l''intensité.',
  null, null, null, false),

((select id from public.domains where slug='sante'), 2, 2,
  'L''assiette anti-fringale — protéines au petit-déjeuner', '10 min', 'Action nutrition',
  'Demain matin, remplace ton petit-déjeuner habituel par un repas avec au moins 20g de protéines : 3 œufs, 150g de fromage blanc, 200g de skyr, ou une poignée d''amandes + jambon. Note si tu as eu faim avant midi.',
  'Flavio Guionneau : "Les fringales de 11h et de 16h ne sont pas un manque de volonté — elles sont la conséquence directe d''un petit-déjeuner trop sucré." Les protéines stimulent la leptine (hormone de satiété) pendant 4 à 6 heures.',
  'Pas de magie — juste de la biochimie.',
  'repas', 'Repas équilibrés cette semaine', 'Avec ce petit-déjeuner protéiné compris', true),

((select id from public.domains where slug='sante'), 2, 3,
  'Objectif 6 000 pas aujourd''hui — comment tu vas y arriver ?', '5 min + journée', 'Objectif chiffré',
  'Avant de commencer ta journée : comment vas-tu atteindre 6 000 pas aujourd''hui ? Nomme 2 moments concrets (10 min le matin, marche à la pause déjeuner…). Ce soir : note le chiffre réel atteint.',
  'Passer de 4 000 à 6 000 pas réduit le risque de maladies cardiovasculaires de 30 % (British Journal of Sports Medicine, 2022). 6 000 pas, c''est 45 minutes de marche réparties dans la journée.',
  'Faisable même les jours de bureau si on l''anticipe.',
  'pas', 'Tes pas aujourd''hui', 'Objectif : 6 000 — qu''as-tu atteint ?', true),

((select id from public.domains where slug='sante'), 2, 4,
  'Remplace 1 aliment ultra-transformé par semaine', '5 min', 'Substitution',
  'Flavio Guionneau ne dit pas "supprime" — il dit "remplace". Identifie 1 aliment ultra-transformé que tu consommes régulièrement. Trouve 1 alternative concrète. Note laquelle.',
  'L''alimentation ultra-transformée représente 30 à 60 % de l''apport calorique des Français — pas par gourmandise, mais par disponibilité et praticité (INSERM, 2023). "Quand tu réduis les ultra-transformés, ton corps répond en quelques jours."',
  'Pas besoin de tout changer — juste une chose à la fois.',
  'repas', 'Repas équilibrés cette semaine', 'La substitution compte comme un repas amélioré', true),

((select id from public.domains where slug='sante'), 2, 5,
  'Bilan 21 jours — compare tes 5 métriques au départ', '5 min', 'Comparaison avant/après',
  'Reviens sur tes mesures du Niveau 0. Pour chaque métrique : où tu en étais, où tu en es aujourd''hui. Calcule le delta. Quel est le chiffre dont tu es le plus fier ?',
  'La comparaison rétrospective est le moteur de motivation le plus puissant. L''être humain est mauvais pour sentir les changements progressifs — on s''y habitue. Mais les chiffres, eux, ne mentent pas.',
  'Ce bilan est souvent le moment où les gens décident de continuer sérieusement.',
  'pas', 'Tes pas/jour actuels', 'Compare à ta baseline du niveau 0', true);

-- Niveau 3 — L''optimisation
insert into public.challenges (domain_id, level_index, order_index, title, duration, type, question, science_text, insight_text, metric_key, metric_label, metric_sub, is_measure) values
((select id from public.domains where slug='sante'), 3, 0,
  'La surcharge progressive — augmente d''une rep par semaine', '3 min', 'Principe sport',
  'Reprends ton exercice préféré. Si tu faisais 3 × 10, passe à 3 × 11 cette semaine. Une répétition. Juste une. Note ton exercice et ton nouveau nombre de répétitions.',
  'Tibo InShape : "Le muscle ne grandit que si tu lui donnes une raison de le faire." La surcharge progressive est le principe n°1 du développement musculaire. +1 rep/semaine = doublement des capacités en 1 an.',
  'Le corps est une machine d''adaptation.',
  'seances', 'Séances avec surcharge progressive cette semaine', 'Séances où tu as augmenté le défi vs la semaine dernière', true),

((select id from public.domains where slug='sante'), 3, 1,
  'Mesure ton hydratation sur 5 jours — atteins 1,5 L chaque jour', 'Tracking 5j', 'Objectif précis',
  'Pendant 5 jours : tu bois 1,5 L minimum. Note chaque soir si tu as atteint l''objectif ou non. À la fin des 5 jours, rentre ta moyenne journalière.',
  '1,5 L/jour est le seuil minimum recommandé par l''ANSES pour maintenir les fonctions cognitives optimales. Au-delà, les bénéfices additionnels sont moindres — l''objectif n''est pas de boire le plus possible.',
  'Éliminer la déshydratation chronique qui affecte chaque cellule.',
  'hydra', 'Hydratation moyenne sur 5 jours', 'Objectif : 1,5 L — qu''as-tu atteint en moyenne ?', true),

((select id from public.domains where slug='sante'), 3, 2,
  'Décrypte tes macronutriments — 1 journée complète', '10 min', 'Éducation nutrition',
  'Utilise une appli (MyFitnessPal, Cronometer) pour tracker TOUT ce que tu manges pendant 1 journée. Note tes apports en protéines, glucides, lipides. Pas pour restreindre — pour comprendre.',
  'Flavio Guionneau : "Comprendre ce que tu manges, c''est te donner le pouvoir de faire des choix conscients." La plupart des Français mangent 2× moins de protéines qu''il ne faudrait (objectif : 1,6g/kg de poids de corps).',
  'Une seule journée de tracking révèle tout.',
  'repas', 'Repas équilibrés cette semaine', 'Avec ta journée de suivi des macros', true),

((select id from public.domains where slug='sante'), 3, 3,
  'Le sommeil et la récupération — mesure ton impact', '3 min', 'Récupération',
  'Pendant 3 jours, note : heure de coucher réelle, heure de réveil, énergie le lendemain sur 10. Cherche le pattern : à partir de combien d''heures tu te sens vraiment bien ?',
  'Matthew Walker (Why We Sleep) : "Le sommeil est l''acte de performance le plus efficace que la science connaît." En dessous de 7h : cortisol en hausse, testostérone en chute, appétit calorique +24 %.',
  'La récupération n''est pas passive — c''est quand le muscle se reconstruit.',
  null, null, null, false),

((select id from public.domains where slug='sante'), 3, 4,
  'Mesure ta progression — photos et tour de taille', '5 min', 'Mesure progression',
  'Prends 3 photos (face, profil, dos) dans les mêmes conditions qu''au départ. Mesure ton tour de taille au nombril. Compare à ta première mesure. Note le delta et ta nouvelle estimation de masse grasse.',
  'La balance est le pire indicateur de progression au début — elle ne distingue pas la perte de graisse du gain musculaire. Le tour de taille et les photos sont objectifs et motivants.',
  'Tibo InShape : "Tes photos dans 3 mois seront ta meilleure récompense."',
  'masse', 'Taux de masse grasse actualisé', 'Nouvelle estimation — même méthode qu''au départ', true);

-- Niveau 4 — Le lifestyle
insert into public.challenges (domain_id, level_index, order_index, title, duration, type, question, science_text, insight_text, metric_key, metric_label, metric_sub, is_measure) values
((select id from public.domains where slug='sante'), 4, 0,
  'Ton "pourquoi" profond — écris-le en 5 lignes', '5 min', 'Fondation identité',
  'Au-delà de "perdre du poids" ou "être en forme" — quelle est la vraie raison pour laquelle tu prends soin de ton corps ? L''énergie pour tes enfants ? La santé mentale ? L''exemple que tu veux donner ? Nomme-la précisément.',
  'Les personnes qui ont un "pourquoi" profond tiennent leurs habitudes 4× plus longtemps que celles motivées par l''apparence seule (Health Psychology, 2019). Tibo InShape : "Le jour où tu fais du sport pour comment tu te sens — pas pour comment tu es perçu — tu ne t''arrêtes plus."',
  'Le passage de la motivation à l''identité.',
  null, null, null, false),

((select id from public.domains where slug='sante'), 4, 1,
  'Conçois ton programme personnel — 4 semaines', '15 min', 'Planification longue',
  'Sur une feuille ou une appli : planifie tes 4 prochaines semaines de sport. Jours, types de séances, progression. Pas parfait — réaliste. Note tes 3 séances de la semaine 1.',
  'Le programme écrit multiplie par 2,5 la probabilité de tenir ses séances sur 30 jours. La planification longue active le cortex préfrontal (décision rationnelle) plutôt que le système limbique (résistance émotionnelle).',
  'La différence entre décider le dimanche et improviser le mercredi soir épuisé.',
  'seances', 'Séances planifiées pour les 4 semaines', 'Nombre total de séances dans ton plan', true),

((select id from public.domains where slug='sante'), 4, 2,
  'Bilan trimestriel — les 5 métriques, avant vs maintenant', '10 min', 'Bilan complet',
  'Reprends chaque métrique du Niveau 0. Calcule le delta exact pour chacune. Note le total de tes progrès : pas/jour, séances/sem, repas équilibrés/sem, hydratation, masse grasse.',
  'Le bilan trimestriel est ce que les meilleurs athlètes font systématiquement — pas pour souffrir sur leurs manques, mais pour mesurer objectivement. La progression est souvent bien meilleure qu''estimée.',
  'C''est ça qui donne l''envie de continuer encore 3 mois.',
  'masse', 'Taux de masse grasse bilan trimestriel', 'Ta dernière mesure pour clôturer ce niveau', true),

((select id from public.domains where slug='sante'), 4, 3,
  'Quel défi sportif veux-tu relever dans les 12 prochains mois ?', '3 min', 'Projection',
  'Un 5 km, une série de pompes consécutives, un sport que tu n''as jamais essayé ? Fixe-toi 1 objectif sportif ambitieux mais atteignable pour les 12 prochains mois. Note la première action concrète cette semaine.',
  'Tibo InShape : "L''objectif n''est pas la destination — il est la direction." Les personnes qui se fixent un défi sportif concret s''entraînent 37 % plus régulièrement que celles avec un objectif flou.',
  'Le défi crée la structure, la structure crée l''habitude, l''habitude crée l''identité.',
  'seances', 'Séances sport cette semaine vers ton objectif', 'Première semaine vers ton défi annuel', true);

-- ─── FINANCES — 18 défis ──────────────────────────────────────
insert into public.challenges (domain_id, level_index, order_index, title, duration, type, question, science_text, insight_text, metric_key, metric_label, metric_sub, is_measure) values
-- Niveau 0
((select id from public.domains where slug='finances'), 0, 0, 'La boîte noire : tes dépenses du mois', '2 min', 'Observation', 'Estime tes dépenses du mois sans regarder ton compte, puis vérifie l''écart réel. Quel est le pourcentage d''erreur ?', 'L''écart moyen entre dépenses estimées et réelles est de 40 % (étude BNP Paribas, 2022). Le cerveau sous-estime systématiquement les petites dépenses fréquentes.', 'La prise de conscience est le premier pas.', null, null, null, false),
((select id from public.domains where slug='finances'), 0, 1, 'Regarde ton solde bancaire 7 matins de suite', '1 min/j × 7', 'Streak', 'Chaque matin pendant 7 jours : ouvre ton application bancaire, regarde ton solde, ferme. Juste observer, sans agir. Note ton niveau de stress de 1 à 10 chaque jour.', 'L''évitement financier aggrave l''anxiété. L''exposition répétée à l''information (même inconfortable) réduit le stress de 60 % en 2 semaines (thérapie d''exposition cognitive).', 'La connaissance réduit l''anxiété — toujours.', null, null, null, false),
((select id from public.domains where slug='finances'), 0, 2, 'Liste tes 5 plus grosses dépenses du mois', '3 min', 'Analyse', 'D''abord de mémoire : liste tes 5 plus grosses dépenses estimées. Puis vérifie dans ton compte. Combien étaient dans le bon ordre ?', 'Les dépenses perçues comme importantes sont sous-estimées de 25 % en moyenne. Les petites dépenses récurrentes (cafés, apps, livraisons) sont oubliées à 70 %.', 'Ce que tu ne vois pas, tu ne peux pas le contrôler.', null, null, null, false),
((select id from public.domains where slug='finances'), 0, 3, 'Combien coûte ta semaine en petits achats < 10 € ?', '2 min', 'Calcul', 'Parcours tes transactions de la semaine. Additionne tous les achats inférieurs à 10 €. Multiplie par 52. Quel est le total annuel ?', 'Les micro-achats représentent en moyenne 23 % du budget des 25-35 ans — soit 3 500 €/an. Invisibles au quotidien, massifs sur l''année.', 'L''effet latte factor — bien réel.', null, null, null, false),
-- Niveau 1
((select id from public.domains where slug='finances'), 1, 0, 'Tes €47 invisibles — audit des abonnements', '3 min', 'Audit', 'Trouve TOUS tes abonnements récurrents : streaming, apps, salle de sport, box, logiciels... Totalise. Annualise. Combien de mois de salaire ça représente ?', 'Le Français moyen dépense 47 €/mois en abonnements oubliés ou sous-utilisés (source : Crédit Agricole, 2023). Sur 10 ans avec placement à 5 % : 7 100 €.', 'Ce que tu ne surveilles pas grossit.', null, null, null, false),
((select id from public.domains where slug='finances'), 1, 1, 'L''achat impulsif de la semaine', '2 min', 'Réflexion', 'Identifie l''achat impulsif de cette semaine — ou de la dernière si cette semaine tu n''en as pas fait. Nomme-le sans te juger. Quel était le déclencheur réel ?', 'Les achats impulsifs représentent 40 % des dépenses non planifiées. Les 3 déclencheurs principaux : stress (47 %), ennui (31 %), promotion (22 %).', 'Identifier ne juge pas — ça libère.', null, null, null, false),
((select id from public.domains where slug='finances'), 1, 2, 'Calcule ton ratio 50/30/20 ce mois', '3 min', 'Budget', 'Classe tes dépenses du mois en 3 catégories : besoins (loyer, courses, transport), envies (restos, loisirs, shopping), épargne. Quel est ton ratio actuel ?', 'La règle 50/30/20 (Elizabeth Warren) est le framework budgétaire le plus étudié. Les Français épargnent en moyenne 15 % — mais seulement 8 % de manière volontaire et régulière.', 'Ce que tu mesures s''améliore.', null, null, null, false),
((select id from public.domains where slug='finances'), 1, 3, 'Le prix de ton café annualisé', '2 min', 'Calcul', 'Combien de cafés achètes-tu par semaine hors de chez toi ? Multiplie par leur prix moyen, puis par 52 semaines. Note le total annuel. Jugement interdit.', 'Annualiser les petits plaisirs n''est pas pour les supprimer — c''est pour les choisir consciemment. 3 cafés à 2,50 € = 390 €/an. Savoir que tu choisis ce plaisir change tout.', 'Le but n''est pas de ne plus boire de café.', null, null, null, false),
((select id from public.domains where slug='finances'), 1, 4, 'Supprime 1 abonnement inutile maintenant — pas demain', '3 min', 'Action directe', 'Reprends ta liste d''abonnements du défi précédent. Identifie le moins utilisé. Va sur le site. Résilie maintenant, pas dans un onglet ouvert "pour plus tard".', 'La procrastination sur les petites décisions financières coûte en moyenne 340 €/an par personne (étude Banque de France). La règle : si tu l''as identifié, agis dans la minute.', 'Décider maintenant coûte 0 €.', null, null, null, false),
((select id from public.domains where slug='finances'), 1, 5, 'Identifie tes 3 déclencheurs d''achat impulsif', '3 min', 'Comportemental', 'Stress, ennui, promo, comparaison sociale, fatigue décisionnelle… Parmi ces déclencheurs, lesquels sont tes 3 principaux ? Comment pourrais-tu créer une friction entre le déclencheur et l''achat ?', 'Créer une friction de 10 minutes entre l''envie et l''achat réduit les achats impulsifs de 58 % (Journal of Consumer Research). La règle des 24h pour tout achat > 50 €.', 'La friction est ton meilleur ami financier.', null, null, null, false),
-- Niveau 2
((select id from public.domains where slug='finances'), 2, 0, 'Se payer en premier — virement automatique', '3 min', 'Action', 'Programme aujourd''hui un virement automatique le jour de ton salaire, même 50 €, vers un compte épargne séparé. Si tu en as déjà un, augmente-le de 10 €.', 'L''épargne automatique pré-salaire est la variable la plus corrélée à l''accumulation patrimoniale à long terme. Warren Buffett : "Ne garde pas ce qui reste après dépenses — dépense ce qui reste après épargne."', 'Ce que tu ne vois pas, tu ne le dépenses pas.', null, null, null, false),
((select id from public.domains where slug='finances'), 2, 1, 'Combien de mois tu tiens sans salaire ?', '2 min', 'Calcul', 'Calcule ton "runway" : épargne liquide disponible ÷ dépenses mensuelles fixes. Combien de mois tu tiens si ton salaire s''arrête demain ?', 'L''objectif recommandé est 3 à 6 mois de dépenses en épargne de précaution. En France, 40 % des actifs n''ont pas 1 mois d''épargne de précaution.', 'La liberté commence par la sécurité.', null, null, null, false),
((select id from public.domains where slug='finances'), 2, 2, 'Ouvre un Livret A ou LDDS si tu n''en as pas', '5 min', 'Action fondatrice', 'Si tu n''as pas de Livret A ou LDDS, ouvre-en un aujourd''hui via ton application bancaire. Si tu en as un, vérifie s''il est au maximum (22 950 € pour le Livret A).', 'Le Livret A est le produit d''épargne le plus accessible de France — disponible à tout moment, sans risque, et defiscalisé. Seulement 82 % des Français en ont un, mais beaucoup le laissent vide.', 'L''outil le plus simple reste le plus sous-utilisé.', null, null, null, false),
((select id from public.domains where slug='finances'), 2, 3, 'L''inflation silencieuse — ton livret perd combien ?', '2 min', 'Prise de conscience', 'Calcule : si ton Livret A est à 3 % et l''inflation est à 2,5 %, ton gain réel est de 0,5 %. Sur 10 000 €, ça fait 50 €/an. À quel rendement réel ton épargne travaille-t-elle vraiment ?', 'L''épargne non investie perd en moyenne 2 % de pouvoir d''achat par an sur 10 ans. Le livret protège — mais n''enrichit pas. La différence entre "ne pas perdre" et "gagner" est là.', 'Comprendre pour choisir, pas pour paniquer.', null, null, null, false),
((select id from public.domains where slug='finances'), 2, 4, 'Vérifie si tu es éligible au LEP', '2 min', 'Optimisation', 'Le Livret d''Épargne Populaire (LEP) est à 4 % (vs 3 % pour le Livret A). Conditions : revenu fiscal de référence < 21 393 € pour 1 part. Vérifie ta dernière feuille d''impôts. Es-tu éligible ?', '60 % des Français sont éligibles au LEP — mais seulement 20 % l''ont ouvert. C''est le meilleur taux garanti sans risque disponible en France. 1 % de plus sur 10 000 € = 100 €/an de plus.', 'Le meilleur investissement sans risque que 80 % des éligibles ignorent.', null, null, null, false),
-- Niveau 3
((select id from public.domains where slug='finances'), 3, 0, 'PEA vs Assurance-Vie — comprends la différence', '3 min', 'Pédagogie', 'PEA : investi en actions européennes, exonéré d''impôt après 5 ans, plafond 150k€. Assurance-Vie : enveloppe flexible (fonds €, actions, SCPI), avantage fiscal après 8 ans. Dans quel ordre les ouvrir selon ta situation ?', 'Le PEA et l''Assurance-Vie sont les deux enveloppes fiscales incontournables pour l''investissement en France. L''horloge fiscale commence à l''ouverture — pas au premier versement.', 'Ouvrir maintenant avec 1 € démarre le compteur.', null, null, null, false),
((select id from public.domains where slug='finances'), 3, 1, 'Simulation intérêts composés — 20 ans à 7 %', '3 min', 'Simulation', '100 €/mois investis à 7 % pendant 20 ans = 52 000 € versés, mais 61 000 € de plus en intérêts = 113 000 € au total. Calcule ta propre simulation : combien peux-tu investir/mois ? Sur combien d''années ?', 'Albert Einstein aurait dit que les intérêts composés sont la 8e merveille du monde. La réalité : 100 €/mois à 7 % pendant 30 ans = 121 000 € de gains pour 36 000 € investis. Le temps est la variable clé.', 'Commencer maintenant vs dans 5 ans = 40 000 € de différence.', null, null, null, false),
((select id from public.domains where slug='finances'), 3, 2, 'L''horloge du PEA — ouvre-le aujourd''hui avec 1 €', '3 min', 'Action urgente', 'Ouvre ton PEA aujourd''hui si tu n''en as pas. Verse 1 € (minimum requis). L''horloge fiscale des 5 ans démarre aujourd''hui. Dans 5 ans, tes plus-values seront exonérées d''impôt.', 'Chaque année sans PEA ouvert est une année de délai fiscal perdue. Un PEA ouvert à 25 ans avec 1 € génère une exonération fiscale active à 30 ans — avant même d''avoir sérieusement investi.', 'Le meilleur moment pour ouvrir un PEA : il y a 5 ans. Le second meilleur : maintenant.', null, null, null, false);

-- ─── TRAVAIL — 17 défis ───────────────────────────────────────
insert into public.challenges (domain_id, level_index, order_index, title, duration, type, question, science_text, insight_text, metric_key, metric_label, metric_sub, is_measure) values
((select id from public.domains where slug='travail'), 0, 0, 'Note ton énergie à 18h pendant 7 jours', '1 min/j × 7', 'Tracking', 'Chaque soir pendant 7 jours : note ton énergie à 18h sur 10, ta tâche principale de la journée, et si elle t''a plutôt donné ou pris de l''énergie.', '90 % des Millennials accordent une importance primordiale au sens de leur travail — et seulement 30 % estiment l''avoir trouvé. La première étape : mesurer.', 'Tu ne peux pas améliorer ce que tu ne mesures pas.', null, null, null, false),
((select id from public.domains where slug='travail'), 0, 1, 'Quelle réunion t''a le plus drainé cette semaine ?', '2 min', 'Observation', 'Pense à toutes les réunions de cette semaine. Laquelle t''a le plus épuisé ? Pourquoi précisément — contenu, participants, durée, inutilité ?', 'Les cadres passent en moyenne 23h/semaine en réunion — dont 67 % sont jugées improductives par les participants eux-mêmes (Harvard Business Review).', 'Nommer le problème, c''est déjà le résoudre à moitié.', null, null, null, false),
((select id from public.domains where slug='travail'), 0, 2, 'Combien d''heures tu travailles vraiment ?', '2 min', 'Mesure', 'Heures de présence au bureau ou devant l''ordi ≠ heures de travail réel. Estime honnêtement : sur tes heures "de travail", combien sont réellement productives ?', 'Étude Microsoft : seulement 3h/8h sont réellement productives pour le travailleur moyen. Le reste : réunions non essentielles, interruptions, navigation.', 'La vérité libère — même quand elle surprend.', null, null, null, false),
((select id from public.domains where slug='travail'), 0, 3, 'Quelle tâche t''a donné le plus d''énergie cette semaine ?', '2 min', 'Identification', 'Parmi toutes tes tâches de la semaine, laquelle t''a donné de l''énergie plutôt qu''elle ne t''en a pris ? Sois précis : quelle tâche exactement, et pourquoi ?', 'Mihaly Csikszentmihalyi sur le "flow" : les tâches qui correspondent à ton niveau de compétence et qui sont légèrement challengeantes créent un état optimal. C''est là que tu es le plus efficace.', 'Ton futur idéal est dans ces moments-là.', null, null, null, false),
-- Niveau 1
((select id from public.domains where slug='travail'), 1, 0, 'Calcule ton ratio subi/choisi cette semaine', '3 min', 'Audit', 'Classe chaque heure de ta semaine de travail en "subi" (imposé, sans valeur pour toi) ou "choisi" (contribue à tes objectifs, te donne de l''énergie). Quel est ton ratio ?', 'Les travailleurs qui perçoivent avoir de l''autonomie sur 50 %+ de leur temps ont un niveau d''engagement 3× supérieur et un taux de burn-out 2× inférieur (Gallup, 2023).', 'Tu ne peux pas tout choisir — mais tu peux changer le ratio.', null, null, null, false),
((select id from public.domains where slug='travail'), 1, 1, 'Ta dernière heure de flow au travail', '2 min', 'Identification', 'C''était quand ? Sur quoi ? Tu avais perdu la notion du temps ? Quelles conditions étaient réunies : seul, environnement calme, tâche claire, deadline proche ?', 'Le flow (Csikszentmihalyi) est l''état de performance optimal : objectif clair + compétence adaptée + feedback immédiat. Les travailleurs en flow sont 5× plus productifs.', 'Identifier les conditions du flow pour les recréer.', null, null, null, false),
((select id from public.domains where slug='travail'), 1, 2, '3 décisions professionnelles à refaire différemment', '3 min', 'Rétrospective', 'Parmi tes décisions professionnelles de ce mois, lesquelles referais-tu différemment ? Pas pour te flageller — pour extraire la leçon opérationnelle.', 'La rétrospective régulière (1x/mois) est la pratique la plus corrélée à la progression professionnelle rapide, selon une étude Harvard Business School sur 10 ans.', 'La leçon non extraite se répète.', null, null, null, false),
((select id from public.domains where slug='travail'), 1, 3, 'Les 3 tâches chronophages à faible valeur', '3 min', 'Analyse', 'Quelles sont les 3 tâches qui occupent le plus de ton temps pour le moins de valeur créée ? Si tu pouvais les déléguer, automatiser ou supprimer, quel serait l''impact ?', 'Le principe de Pareto : 20 % des activités créent 80 % de la valeur. Identifier le bas du tableau permet de libérer du temps pour le haut.', 'Moins fait mieux vaut plus fait mal.', null, null, null, false),
((select id from public.domains where slug='travail'), 1, 4, 'La chose non dite à ton manager', '3 min', 'Clarté', 'Écris en 3 lignes ce que tu n''as jamais dit à ton manager ou à ton équipe. Pas pour l''envoyer — pour clarifier ta propre pensée. Qu''est-ce qui ressort ?', 'Les non-dits professionnels créent une charge cognitive silencieuse estimée à 2h/semaine de rumination. Les mettre sur papier, même sans les envoyer, libère 80 % de ce poids.', 'La clarté interne précède la clarté externe.', null, null, null, false),
-- Niveau 2
((select id from public.domains where slug='travail'), 2, 0, 'Si tu pouvais changer 1 seule chose de ton job demain', '2 min', 'Clarification', 'Une seule chose. La réponse qui vient immédiatement, avant que le mental ne rationalise. Qu''est-ce que ça révèle sur tes besoins réels ?', 'La contrainte "une seule chose" force le cerveau à identifier la vraie priorité, pas la liste de souhaits. C''est la technique de Jeff Bezos pour prendre des décisions importantes.', 'La première réponse est souvent la vraie.', null, null, null, false),
((select id from public.domains where slug='travail'), 2, 1, 'Tes 3 compétences dans le top 10 % de ton entourage', '3 min', 'Inventaire', 'Quelles sont les 3 choses pour lesquelles les gens te demandent naturellement de l''aide ? Pas ce que tu penses être bon — ce pour quoi les autres te sollicitent.', 'Scott Adams (Dilbert) : "Devenir dans le top 20 % dans 2 ou 3 compétences crée une combinaison rare qui vaut plus que d''être dans le top 1 % dans une seule." L''intersection crée la valeur.', 'Ton unicité est souvent invisible à tes yeux.', null, null, null, false),
((select id from public.domains where slug='travail'), 2, 2, 'Ton idéal de semaine de travail en 5 lignes', '5 min', 'Vision', 'Décris ta semaine de travail idéale : combien d''heures, avec qui, sur quoi, où, dans quel état d''esprit ? Pas ce qui est possible — ce qui serait idéal.', 'L''exercice de la "semaine idéale" (Tim Ferriss) révèle systématiquement des priorités cachées. 73 % des participants découvrent qu''ils veulent moins travailler et mieux — pas le contraire.', 'La vision précède le changement.', null, null, null, false),
((select id from public.domains where slug='travail'), 2, 3, '3 compétences à développer dans les 12 prochains mois', '3 min', 'Planification', 'Pour aller où tu veux aller professionnellement dans 3 ans, quelles sont les 3 compétences qui manquent le plus à ton profil actuel ? Sois spécifique.', 'Les professionnels qui se fixent des objectifs de développement compétences précis progressent 2,3× plus vite que ceux avec des objectifs vagues. La spécificité active le système réticulaire activateur.', 'Savoir ce qui manque est déjà avancer.', null, null, null, false),
-- Niveau 3
((select id from public.domains where slug='travail'), 3, 0, 'Envoie un message à quelqu''un dans le secteur qui t''attire', '5 min', 'Action concrète', 'Identifie 1 personne dans le métier ou secteur qui t''attire. Envoie-lui un message court pour 30 minutes d''échange : présente-toi en 2 lignes, explique pourquoi tu la contactes, propose un créneau.', 'Les opportunités professionnelles viennent à 80 % du réseau — et à 95 % des contacts faibles (personnes qu''on ne connaît pas bien). Envoyer 1 message par semaine = 52 opportunités par an.', 'La pire réponse possible est "non" — et ça ne coûte rien.', null, null, null, false),
((select id from public.domains where slug='travail'), 3, 1, 'Bloque 1h/semaine pour ton projet — 4 semaines', '2 min', 'Engagement', 'Ouvre ton agenda. Bloque 1h par semaine pendant les 4 prochaines semaines pour travailler sur ce qui compte pour ta trajectoire professionnelle. Traite ce créneau comme une réunion avec ton meilleur client.', 'Les personnes qui planifient leurs projets de développement dans l''agenda ont 3× plus de chances de les réaliser. Le calendrier est le reflet de tes vraies priorités.', 'Ce qui n''est pas dans l''agenda n''existe pas.', null, null, null, false),
((select id from public.domains where slug='travail'), 3, 2, 'Ton objectif professionnel à 3 ans en 1 phrase précise', '3 min', 'Vision', 'Formule ton objectif professionnel dans 3 ans en une seule phrase la plus précise possible. Pas "être épanoui" — mais "diriger une équipe de 5 dans une startup B2B SaaS comme CTO".', 'Les objectifs précis activent le réseau de saillance (RAS) du cerveau qui filtre automatiquement les opportunités pertinentes. Un objectif flou produit une vie floue.', 'La précision est une forme de courage.', null, null, null, false),
((select id from public.domains where slug='travail'), 3, 3, 'Identifie un mentor potentiel dans ton réseau', '3 min', 'Réseau', 'Pense à quelqu''un dans ton réseau avec 5 à 10 ans d''avance sur ta trajectoire souhaitée. Comment pourrais-tu l''approcher pour un échange régulier ou ponctuel ?', 'Les professionnels avec un mentor progressent 20 % plus vite et gagnent en moyenne 29 % de plus au bout de 5 ans. Le mentorat informel (déjeuner 1x/trimestre) est souvent aussi efficace que le formel.', 'Un mentor économise 5 ans d''erreurs.', null, null, null, false);

-- ─── ENTREPRENEURIAT — 17 défis ───────────────────────────────
insert into public.challenges (domain_id, level_index, order_index, title, duration, type, question, science_text, insight_text, metric_key, metric_label, metric_sub, is_measure) values
((select id from public.domains where slug='entrepreneuriat'), 0, 0, 'Depuis combien de temps penses-tu à entreprendre sans agir ?', '2 min', 'Prise de conscience', 'En mois, honnêtement. Pas pour culpabiliser — pour mesurer. Plus le nombre est grand, plus il y a quelque chose à explorer.', '3 Français sur 10 considèrent l''entrepreneuriat comme choix de carrière idéal. La plupart n''agissent jamais. Le délai moyen entre "l''idée" et "l''action" est de 4 ans.', 'Mesurer le délai, c''est le premier pas pour le réduire.', null, null, null, false),
((select id from public.domains where slug='entrepreneuriat'), 0, 1, 'C''est quoi exactement qui te retient — en une phrase', '2 min', 'Diagnostic', 'La vraie raison, pas la version socialement acceptable. Peur de l''échec ? Du regard des autres ? De l''argent ? De ne pas savoir par où commencer ? Note-la sans te censurer.', 'Les 3 freins principaux à l''entrepreneuriat en France : peur de l''échec (45 %), manque de capitaux perçu (38 %), manque de compétences perçu (29 %). Les deux derniers sont des freins surestimés.', 'Le frein nommé est un frein qu''on peut travailler.', null, null, null, false),
((select id from public.domains where slug='entrepreneuriat'), 0, 2, '3 personnes de ton entourage qui ont lancé quelque chose', '2 min', 'Référence', 'Pense à 3 personnes qui ont lancé une activité, même petite. Qu''est-ce qui les distinguait de ceux qui n''ont pas sauté le pas ? Compétences ? Situation ? Personnalité ?', 'L''effet de référence sociale est puissant : avoir un entrepreneur dans son entourage proche multiplie par 3,5 la probabilité d''entreprendre soi-même. Si tu n''en as pas, il faut en trouver.', 'L''environnement façonne le destin entrepreneurial.', null, null, null, false),
((select id from public.domains where slug='entrepreneuriat'), 0, 3, 'Combien d''heures pourrais-tu dédier à un projet parallèle ?', '2 min', 'Ressources', 'Regarde ta semaine réelle. Compte les heures de scrolling, de série, de temps "vide". Combien pourrais-tu en convertir en temps de projet sans sacrifier ton équilibre ?', 'La plupart des entrepreneurs à succès ont commencé en side project avec 5 à 10h/semaine. Selon une étude de Stanford, 70 % des entrepreneurs B2B à succès n''ont pas quitté leur emploi avant d''avoir leurs 3 premiers clients.', 'Le temps existe — il est juste mal réparti.', null, null, null, false),
-- Niveau 1
((select id from public.domains where slug='entrepreneuriat'), 1, 0, 'Si le succès était garanti, quelle activité lancerais-tu ?', '3 min', 'Clarification', 'Enlève la peur de l''échec de l''équation. Si tu savais à 100 % que ça marchait : quelle activité lancerais-tu ? Et surtout : est-ce que tu le ferais même si c''était difficile ?', 'La question "et si c''était difficile ?" est le filtre de la vraie vocation. Tout le monde veut le résultat facile. Ceux qui réussissent veulent aussi le processus difficile.', 'La vraie passion est celle qui survit à la difficulté.', null, null, null, false),
((select id from public.domains where slug='entrepreneuriat'), 1, 1, '3 problèmes que tu résouds mieux que la moyenne', '3 min', 'Inventaire', 'Quels sont les 3 problèmes pour lesquels les gens viennent naturellement te demander de l''aide ? Pas les compétences que tu penses avoir — celles pour lesquelles on te sollicite réellement.', 'Les meilleures idées business viennent de problèmes que l''entrepreneur a lui-même vécu ou résolu. 65 % des startups à succès ont été fondées sur la douleur personnelle du fondateur.', 'Ton expertise invisible est souvent ton meilleur produit.', null, null, null, false),
((select id from public.domains where slug='entrepreneuriat'), 1, 2, 'Pour chaque problème : qui paierait et combien ?', '3 min', 'Validation', 'Pour chacun des 3 problèmes identifiés : imagine une personne qui souffre de ce problème. Paierait-elle pour que tu le résolves ? Combien ? Sous quelle forme (service, outil, contenu) ?', 'La validation par le "willingness to pay" est le test le plus fiable de la viabilité d''une idée. Un problème réel + une solution simple + un client qui paie = un business.', 'Si personne ne paie, c''est un hobby.', null, null, null, false),
((select id from public.domains where slug='entrepreneuriat'), 1, 3, 'Cherche 3 personnes qui ont réussi dans ce que tu envisages', '5 min', 'Benchmark', 'Pour chaque idée : trouve 3 personnes ou entreprises qui l''ont déjà réalisée. Qu''est-ce qui les a amenées là ? Quel a été leur chemin ?', 'Le benchmark évite l''erreur de croire qu''une idée est originale — ou au contraire qu''elle est impossible. La plupart des business viables existent déjà sous d''autres formes.', 'Si quelqu''un a réussi, le marché existe.', null, null, null, false),
((select id from public.domains where slug='entrepreneuriat'), 1, 4, 'Parle de ton idée à une personne de confiance ce soir', '2 min', 'Test social', 'Choisis quelqu''un qui te dira la vérité, pas quelqu''un qui va te ménager. Explique ton idée en 2 minutes. Observe ta facilité ou ta difficulté à la pitcher — et sa réaction.', '1 conversation client bat 10 heures de business plan (Eric Ries, Lean Startup). Le premier test d''une idée est ta capacité à l''expliquer simplement à quelqu''un qui ne te connaît pas.', 'Si tu ne peux pas l''expliquer simplement, tu ne l''as pas encore.', null, null, null, false),
-- Niveau 2
((select id from public.domains where slug='entrepreneuriat'), 2, 0, 'Identifie un client cible et contacte-le pour 30 min', '5 min', 'Action directe', 'Trouve une personne réelle qui a le problème que tu veux résoudre. Envoie-lui un message aujourd''hui pour 30 minutes d''échange. Pas pour vendre — pour comprendre.', '1 conversation client = plus d''insights que 10 heures de recherche desk. Les startups qui font 20+ interviews clients avant de coder ont un taux de succès 2× supérieur.', 'Le marché te dira ce dont il a besoin — si tu écoutes.', null, null, null, false),
((select id from public.domains where slug='entrepreneuriat'), 2, 1, 'Contacte 5-10 personnes : paieraient-elles pour ta solution ?', '3 min', 'Validation prix', 'Envoie un message simple à 5-10 contacts : "Je travaille sur X. Est-ce que tu rencontres ce problème ? Paierais-tu Y€ pour le résoudre ?" Collecte les réponses. Calcule le taux de "oui".', 'Un taux de "oui" > 30 % sur une proposition non polie = signal fort. La plupart des entrepreneurs font l''erreur de ne poser la question de l''argent qu''après avoir codé 6 mois.', 'Demander à être payé avant de livrer : le test de validation ultime.', null, null, null, false),
((select id from public.domains where slug='entrepreneuriat'), 2, 2, 'Rédige ton offre en 1 phrase', '3 min', 'Clarté message', '"J''aide [qui] à [quel problème] grâce à [quoi]." Exemple : "J''aide les freelances à trouver des clients récurrents grâce à une méthode de contenu en 30 min/semaine." Écris ta version.', 'La phrase de positionnement (value proposition) est le test de clarté le plus important. Si tu ne peux pas la dire en 10 secondes, ton client ne comprendra pas pourquoi te choisir.', 'La clarté convertit. La complexité fuit.', null, null, null, false),
((select id from public.domains where slug='entrepreneuriat'), 2, 3, 'Identifie 3 concurrents directs en 15 minutes', '5 min', 'Analyse marché', 'Cherche 3 entreprises ou personnes qui font déjà quelque chose de similaire. Pour chacune : qu''est-ce qu''elles font bien ? Mal ? Où est le vide que tu pourrais combler ?', 'La concurrence prouve que le marché existe. L''absence de concurrence = soit une niche incroyable, soit personne ne veut payer pour ça. Analyser les avis clients des concurrents révèle les frustrations non résolues.', 'Le vide dans les avis 3 étoiles est ton business plan.', null, null, null, false),
((select id from public.domains where slug='entrepreneuriat'), 2, 4, 'Calcule ton runway — combien de mois sans revenus ?', '3 min', 'Ressources financières', 'Avec ton épargne actuelle : combien de mois tu tiens sans salaire en maintenant ton mode de vie actuel ? Et en mode austérité (dépenses réduites de 40 %) ?', 'La principale cause d''échec des startups est de manquer de cash avant d''avoir trouvé le product-market fit — pas l''idée. Connaître ton runway permet de planifier ta sortie de salariat sereinement.', 'La liberté d''entreprendre commence par la sécurité financière.', null, null, null, false),
-- Niveau 3
((select id from public.domains where slug='entrepreneuriat'), 3, 0, 'Crée ta première landing page — en ligne aujourd''hui', '1h', 'Livrable', 'Une page, une offre, un bouton de contact. Utilise Carrd (5 min), Notion public, ou Google Sites. L''objectif n''est pas la perfection — c''est l''existence en ligne. Lance aujourd''hui.', 'Le principe du "done is better than perfect" appliqué : une landing page imparfaite en ligne génère du feedback réel. Une landing page parfaite dans ta tête ne génère rien.', 'Exister en ligne, même imparfaitement, te rend réel.', null, null, null, false),
((select id from public.domains where slug='entrepreneuriat'), 3, 1, 'Quel objectif de revenus secondaires ce mois ?', '3 min', 'KPI', 'Fixe-toi un objectif de revenus secondaires pour les 30 prochains jours. Même 50 € — juste pour que le premier euro entre. Quelles 3 actions concrètes cette semaine pour y arriver ?', 'Les premiers 100 € sont les plus importants — pas pour l''argent, mais pour la preuve psychologique que quelqu''un paie pour ta valeur. Ça change fondamentalement l''état d''esprit entrepreneurial.', 'Le premier euro prouve que c''est possible.', null, null, null, false),
((select id from public.domains where slug='entrepreneuriat'), 3, 2, 'Définis ton client idéal en 5 caractéristiques', '3 min', 'Ciblage', 'Âge, situation, douleur principale, budget disponible, comportement d''achat. Plus tu es précis, plus ton message convertit. Évite le piège de "tout le monde".', 'Les business qui ciblent un segment précis convertissent 3× mieux que ceux qui visent "tout le monde". Seth Godin : "Si ton produit est pour tout le monde, il n''est pour personne."', 'La précision est une stratégie de croissance.', null, null, null, false),
((select id from public.domains where slug='entrepreneuriat'), 3, 3, 'Rétrospective : 3 choses que tu aurais faites différemment', '5 min', 'Apprentissage', 'Avec ce que tu sais maintenant, quelles sont les 3 choses que tu aurais faites différemment depuis le début de ce parcours entrepreneurial ? Qu''est-ce que ça révèle sur tes prochains pas ?', 'La rétrospective entrepreneuriale régulière est la pratique la plus corrélée à la résilience des fondateurs. Les entrepreneurs qui échouent et rebondissent ont en commun : ils analysent, ils n''évitent pas.', 'L''erreur non analysée se répète — l''erreur analysée devient un avantage.', null, null, null, false);

-- ─── BIEN-ÊTRE — 18 défis ─────────────────────────────────────
insert into public.challenges (domain_id, level_index, order_index, title, duration, type, question, science_text, insight_text, metric_key, metric_label, metric_sub, is_measure) values
((select id from public.domains where slug='bienetre'), 0, 0, 'Ton niveau de stress cette semaine sur 10', '1 min', 'Mesure', 'La première réponse qui vient — pas après réflexion. Note ce chiffre. Sans jugement. Il va servir de baseline.', '35 % des Millennials se déclarent stressés en permanence. La mesure régulière du stress est la première étape de sa régulation — tu ne peux pas gérer ce que tu ne mesures pas.', 'Le chiffre sans jugement est le point de départ.', null, null, null, false),
((select id from public.domains where slug='bienetre'), 0, 1, 'Comment tu décompresses vraiment — pas ce que tu devrais faire', '2 min', 'Diagnostic', 'Quand tu es stressé, que fais-tu réellement pour décompresser ? Séries, scroll, sport, apéro, musique ? Pas la version idéale — la réalité.', 'Les mécanismes de coping réels sont souvent différents des stratégies recommandées. Les connaître permet de les évaluer — certains rechargent réellement, d''autres créent une fausse détente.', 'Connaître son vrai mécanisme avant de le changer.', null, null, null, false),
((select id from public.domains where slug='bienetre'), 0, 2, 'La dernière fois que tu as ressenti de la vraie joie', '2 min', 'Diagnostic', 'Pas du soulagement (fini le projet), pas du plaisir (bon repas) — de la vraie joie spontanée. C''était quand ? Dans quel contexte ? Avec qui ?', 'La distinction joie/soulagement/plaisir est importante : la joie est associée à l''alignement avec ses valeurs. Sa rareté est un signal.', 'Si tu dois chercher longtemps, c''est une information.', null, null, null, false),
((select id from public.domains where slug='bienetre'), 0, 3, '3 personnes qui t''énergisent vs 3 qui t''épuisent', '3 min', 'Relations', 'Fais deux listes : 3 personnes après lesquelles tu te sens mieux, plus léger, plus toi-même. Et 3 personnes après lesquelles tu te sens vidé, lourd, moins bien.', 'Les relations sont le facteur n°1 de bien-être selon la Harvard Study of Adult Development (80 ans de données). La qualité de tes 5 relations les plus proches prédit ta satisfaction de vie mieux que ton salaire.', 'Ton entourage est ton environnement intérieur.', null, null, null, false),
-- Niveau 1
((select id from public.domains where slug='bienetre'), 1, 0, 'Le moment précis qui t''a le plus drainé ce mardi', '2 min', 'Spécificité', 'Pas "le travail en général" ou "la pression". Le moment précis : quelle heure, quelle situation, quelles personnes, quelle tâche. La spécificité transforme le vague en solvable.', 'L''anxiété diffuse et l''anxiété spécifique se traitent différemment. La spécificité active le cortex préfrontal (résolution de problème) plutôt que le système limbique (alarme).', 'Nommer précisément réduit l''intensité émotionnelle.', null, null, null, false),
((select id from public.domains where slug='bienetre'), 1, 1, '3 moments positifs de cette semaine — même petits', '2 min', 'Recadrage', 'Cherche 3 moments de cette semaine, même minuscules, où tu as ressenti quelque chose de positif. Pas les grands événements — les micro-moments.', 'Le biais de négativité (negativity bias) fait que le cerveau enregistre 4× plus fortement les expériences négatives. L''entraîner à détecter le positif est une compétence qui se développe.', 'Ce qu''on cherche, on le trouve.', null, null, null, false),
((select id from public.domains where slug='bienetre'), 1, 2, 'Ta principale préoccupation cette semaine — une seule', '2 min', 'Clarification', 'Pas la liste complète — la principale. Celle qui occupe le plus de bande passante mentale. En une phrase précise.', 'Le mental peut gérer 1 préoccupation centrale avec efficacité. Quand il en jongle 5 en parallèle, la qualité de traitement de chacune s''effondre. Hiérarchiser libère.', 'Ce qui est nommé peut être traité.', null, null, null, false),
((select id from public.domains where slug='bienetre'), 1, 3, 'Tes 3 principales sources d''énergie hors travail', '3 min', 'Inventaire', 'Pas les activités que tu devrais faire — celles qui te rechargent réellement. Sport ? Nature ? Créativité ? Solitude ? Connexion sociale ?', 'Les ressources de bien-être (ressources COR — Conservation of Resources) sont individuelles. Ce qui recharge l''un épuise l''autre. Connaître les siennes permet de les planifier.', 'Planifier ses ressources est une compétence.', null, null, null, false),
((select id from public.domains where slug='bienetre'), 1, 4, 'La décision que tu reportes depuis des semaines', '2 min', 'Clarté', 'Quelle est la décision ou tâche que tu évites depuis le plus longtemps ? Comment ce report pèse-t-il concrètement sur ton bien-être quotidien ?', 'L''effet Zeigarnik : les tâches incomplètes ou décisions évitées créent une charge cognitive permanente — comme des onglets ouverts dans ton cerveau. Les fermer, même en décidant de ne pas agir, libère de l''énergie.', 'Décider de ne pas décider est aussi une décision.', null, null, null, false),
-- Niveau 2
((select id from public.domains where slug='bienetre'), 2, 0, '3 minutes de cohérence cardiaque — maintenant', '3 min', 'Pratique immédiate', 'Inspire 5 secondes par le nez, expire 5 secondes par la bouche. Répète pendant 3 minutes. C''est tout. Note ton niveau de stress avant et après sur 10.', 'La cohérence cardiaque (5 respirations/min) active le système nerveux parasympathique et réduit le cortisol de 20 % en 3 minutes (Institut HeartMath). Pratiquée 3x/jour, elle réduit l''anxiété chronique de 30 %.', 'L''outil le plus simple pour réguler le stress — validé scientifiquement.', null, null, null, false),
((select id from public.domains where slug='bienetre'), 2, 1, 'Écriture libre — 3 lignes sans censure', '3 min', 'Journaling', 'Pose ce que tu as en tête en ce moment. 3 lignes minimum, sans relire, sans corriger. Juste écrire. Qu''est-ce qui sort ?', 'Le journaling expressif réduit l''anxiété de 28 % en 4 semaines (James Pennebaker, Université du Texas). Mettre les pensées en mots les externalise — le cerveau peut alors les "fermer".', 'Ce qui sort de ta tête sur le papier prend moins de place dedans.', null, null, null, false),
((select id from public.domains where slug='bienetre'), 2, 2, '10 minutes sans aucun écran — maintenant', '10 min', 'Expérience', 'Pose ton téléphone, ferme l''ordinateur. 10 minutes. Observe les pensées qui arrivent sans les chasser. Tu peux t''asseoir, marcher, regarder par la fenêtre.', 'Les adultes consultent leur téléphone en moyenne 96 fois par jour (Asurion, 2023). Chaque notification interrompt le fil de pensée pour 23 minutes. 10 minutes sans écran est déjà un déconditionnement puissant.', 'L''ennui est le début de la créativité.', null, null, null, false),
((select id from public.domains where slug='bienetre'), 2, 3, '3 choses concrètes pour lesquelles tu es reconnaissant', '2 min', 'Gratitude', 'Pas génériques ("ma santé", "ma famille") — spécifiques ("la conversation avec X hier", "le café ce matin", "avoir fini Y"). La spécificité déclenche l''émotion réelle.', 'La pratique de gratitude quotidienne augmente le bien-être subjectif de 25 % en 6 semaines (Martin Seligman, University of Pennsylvania). La spécificité est la clé — le cerveau ne répond pas aux généralités.', 'La gratitude est un muscle.', null, null, null, false),
((select id from public.domains where slug='bienetre'), 2, 4, 'Une tâche à déléguer, automatiser ou supprimer', '3 min', 'Allègement', 'Parmi tes obligations régulières, y en a-t-il une que tu pourrais déléguer, automatiser ou tout simplement arrêter — sans vraie conséquence ?', 'La charge mentale (cognitive load) est mesurable. Chaque tâche récurrente occupe de la bande passante, même quand elle n''est pas faite. La simplification délibérée est une compétence de bien-être.', 'Enlever est souvent plus efficace qu''ajouter.', null, null, null, false),
-- Niveau 3
((select id from public.domains where slug='bienetre'), 3, 0, 'Ton score de bien-être moyen ce mois — tendance ?', '2 min', 'Évolution', 'Compare ton score de stress/bien-être de ce mois à celui du mois dernier. Quelle est la tendance ? Qu''est-ce qui a changé dans ta vie qui pourrait expliquer l''évolution ?', 'Le suivi longitudinal du bien-être est le seul moyen de distinguer les fluctuations normales des tendances réelles. La plupart des gens vivent des baisses sans les relier à des causes.', 'La conscience de la tendance permet d''agir avant la crise.', null, null, null, false),
((select id from public.domains where slug='bienetre'), 3, 1, 'Conçois ta transition travail/soirée en 5 minutes', '5 min', 'Design routine', 'Crée un ritual de transition de 5 minutes entre la fin du travail et le début de la soirée. Un signal clair que c''est fini : marche, sport, douche, musique, fermeture des onglets avec intention.', 'L''absence de transition travail/maison est le principal facteur de rumination nocturne (62 % des travailleurs hybrides). Un ritual de 5 minutes réduit le spillover de 40 %.', 'Le signal de fin active la récupération.', null, null, null, false),
((select id from public.domains where slug='bienetre'), 3, 2, 'Lance une méditation guidée de 5 minutes', '5 min', 'Pratique', 'Ouvre Petit Bambou, Headspace, ou cherche "méditation 5 minutes" sur YouTube. Lance. Note ce que tu ressens avant et après — sans attendre que ce soit parfait.', 'La méditation de pleine conscience de 5 min/jour pendant 8 semaines réduit l''amygdale (centre de l''alarme) de façon mesurable en IRM (Sara Lazar, Harvard Medical School).', 'Pas besoin d''une heure. 5 minutes changent le cerveau.', null, null, null, false),
((select id from public.domains where slug='bienetre'), 3, 3, 'Une lettre à ton toi dans 5 ans', '10 min', 'Projection', 'Écris une lettre à la personne que tu seras dans 5 ans. Ce qu''elle aimerait que tu saches ou que tu fasses maintenant. Sans te censurer.', 'L''exercice de la lettre future active le cortex préfrontal et la pensée à long terme, réduisant le biais de présent (qui nous fait sacrifier le futur pour l''immédiat). 20 minutes d''écriture = changement comportemental mesurable à 3 mois.', 'Ton futur toi est réel — il mérite d''être consulté.', null, null, null, false),
((select id from public.domains where slug='bienetre'), 3, 4, 'Une chose dont tu peux être fier cette semaine', '2 min', 'Estime de soi', 'Aussi petite soit-elle. Pas les grandes performances — quelque chose de concret que tu as fait cette semaine dont tu peux être fier.', 'L''auto-compassion (Kristin Neff) est un prédicteur de résilience plus fort que l''estime de soi classique. Célébrer les petites victoires active le circuit de récompense dopaminergique et renforce la motivation intrinsèque.', 'La fierté méritée est un carburant.', null, null, null, false);

-- ─── ÉCOLOGIE — 16 défis ──────────────────────────────────────
insert into public.challenges (domain_id, level_index, order_index, title, duration, type, question, science_text, insight_text, metric_key, metric_label, metric_sub, is_measure) values
((select id from public.domains where slug='ecologie'), 0, 0, 'Tes déplacements de la semaine — quel bilan carbone ?', '3 min', 'Empreinte', 'Liste tous tes déplacements de la semaine : métro, voiture, train, avion. Utilise une règle simple (voiture = 20g CO2/km, avion = 250g/km) pour estimer ton bilan. Quel est le total ?', '6 Millennials sur 10 sont anxieux face au changement climatique mais ne savent pas par où commencer. Le transport représente 30 % de l''empreinte carbone individuelle moyenne en France.', 'Mesurer avant d''agir — toujours.', null, null, null, false),
((select id from public.domains where slug='ecologie'), 0, 1, 'Ta poubelle cette semaine — quels déchets évitables ?', '2 min', 'Observation', 'Pense à ta poubelle de cette semaine. Quels déchets auraient pu être : recyclés (mais ne l''ont pas été) ? Évités (emballages, jetables) ? Compostés ?', 'Les Français recyclent en moyenne 23 % de leurs déchets — vs 50 % en Allemagne. 40 % des aliments achetés sont jetés sans être consommés.', 'La conscience précède le changement.', null, null, null, false),
((select id from public.domains where slug='ecologie'), 0, 2, 'Combien d''apps avec notifications actives sur ton téléphone ?', '2 min', 'Audit numérique', 'Va dans tes paramètres. Compte le nombre d''applications avec notifications activées. Le numérique a une empreinte carbone : 1 email avec pièce jointe = 50g CO2, 1 heure de streaming = 36g CO2.', 'Le numérique représente 3,5 % des émissions mondiales de gaz à effet de serre — davantage que l''aviation civile. En France, le streaming vidéo représente 60 % du trafic internet.', 'La sobriété numérique est une forme d''écologie.', null, null, null, false),
((select id from public.domains where slug='ecologie'), 0, 3, 'Combien de minutes perdues à chercher des infos mal organisées ?', '2 min', 'Mesure', 'Combien de minutes par jour perds-tu à chercher des informations (emails, fichiers, notes) qui devraient être organisées ? Estime le total hebdomadaire.', 'Les travailleurs du savoir passent 2,5h/jour à chercher des informations (McKinsey). Sur un an : 600 heures perdues, soit 25 jours de travail. L''organisation est une forme de durabilité.', 'Organiser est un acte de respect de son temps.', null, null, null, false),
-- Niveau 1
((select id from public.domains where slug='ecologie'), 1, 0, 'Calcule ton empreinte carbone annuelle — nosgestesclimats.fr', '5 min', 'Bilan carbone', 'Va sur nosgestesclimats.fr. Fais le test complet (5 minutes). Note ton résultat en tonnes CO2eq. Compare à la moyenne française (9,2t) et à l''objectif 2050 (2t).', 'L''empreinte carbone moyenne d''un Français est 9,2 tonnes CO2/an — l''objectif est 2 tonnes pour rester sous +1,5°C. Transport et alimentation représentent 50 % du total.', 'Ton chiffre personnel est ton point de départ — pas un jugement.', null, null, null, false),
((select id from public.domains where slug='ecologie'), 1, 1, 'Audit transport ce mois — total et répartition', '3 min', 'Audit', 'Liste toutes tes dépenses transport de ce mois : SNCF, essence, Uber, avion, vélo. Quel est le total en euros ? La répartition par mode ?', 'Passer de la voiture au vélo pour les trajets < 5km réduit l''empreinte transport de 40 % et améliore la santé physique et mentale. 60 % des trajets en voiture en ville font moins de 3km.', 'Le transport choisi révèle les priorités réelles.', null, null, null, false),
((select id from public.domains where slug='ecologie'), 1, 2, 'Parmi 4 postes, les 3 modifications à plus fort impact', '3 min', 'Identification', 'Alimentation, transport, logement, achats — d''après ton bilan carbone, quels sont les 3 changements qui réduiraient le plus ton empreinte ? Sois spécifique.', 'L''alimentation (végétaliser) et le transport (réduire l''avion et la voiture) représentent 80 % du potentiel de réduction individuelle. Le reste est de l''optimisation marginale.', 'Concentre l''énergie sur ce qui compte vraiment.', null, null, null, false),
((select id from public.domains where slug='ecologie'), 1, 3, 'Supprime 3 applications non utilisées depuis 1 mois', '3 min', 'Désencombrement', 'Va dans tes paramètres → gestion des apps → trier par dernière utilisation. Supprime les 3 que tu n''as pas ouvertes depuis plus d''un mois. Note combien de temps ça a pris.', 'Chaque application installée consomme des ressources (processeur, stockage, batterie) même non utilisée. Désinstaller régulièrement améliore les performances et réduit la charge cognitive.', 'Désencombrer le téléphone désencombre l''esprit.', null, null, null, false),
((select id from public.domains where slug='ecologie'), 1, 4, 'Combien d''apps non utilisées depuis 1 mois ?', '2 min', 'Audit organisation', 'Ton système de notes actuel (téléphone, carnet, mémo vocal, post-it) — il te donne confiance que tu ne perds rien d''important, ou génère-t-il de l''anxiété et du désordre ?', 'Un système d''organisation fiable libère la mémoire de travail du cerveau — qui peut alors se consacrer à la pensée créative plutôt qu''à la mémorisation. David Allen (Getting Things Done) : "Ton esprit est fait pour avoir des idées, pas pour les stocker."', 'La confiance dans ton système = tranquillité d''esprit.', null, null, null, false),
-- Niveau 2
((select id from public.domains where slug='ecologie'), 2, 0, 'Choisis ton levier le plus facile cette semaine', '3 min', 'Action', 'Parmi tes habitudes, identifie le changement le plus facile à adopter cette semaine pour réduire ton impact. Quelle action précise, à quel moment de ta journée ?', 'L''action concrète spécifique est 5× plus tenue que la résolution générale. "Manger végétarien le lundi" est 5× plus efficace que "manger moins de viande".', 'Petit et précis bat grand et vague.', null, null, null, false),
((select id from public.domains where slug='ecologie'), 2, 1, 'Choisis 1 endroit pour capturer toutes tes idées', '10 min', 'Organisation', 'Une seule application ou un seul carnet pour capturer TOUTES tes idées et tâches. Configure-la maintenant : vide ta tête de tout ce qui y traîne en 5 minutes.', 'L''inbox universelle (David Allen) élimine l''anxiété de "je vais oublier". Le cerveau dépense de l''énergie à mémoriser les tâches incomplètes — l''externalisation libère cette énergie.', 'Un seul endroit pour tout = zéro perte, zéro anxiety.', null, null, null, false),
((select id from public.domains where slug='ecologie'), 2, 2, 'Notifications : ne garde que les urgentes', '5 min', 'Action numérique', 'Passe en revue chaque application. Pour chacune : est-ce que cette notification est urgente (nécessite une action dans l''heure) ? Si non, désactive. Garde 5 apps maximum avec notifications actives.', 'Chaque notification interrompt le flux de concentration pour 23 minutes en moyenne. Réduire à 5 apps = économie de 2h de concentration par jour.', 'L''attention est ta ressource la plus précieuse.', null, null, null, false),
((select id from public.domains where slug='ecologie'), 2, 3, '1 repas sans viande ni poisson — explore une recette', '1j', 'Action alimentaire', 'Choisis un repas cette semaine sans viande ni poisson que tu n''aurais pas choisi spontanément. Cherche une recette (dal de lentilles, curry de pois chiches, pasta e fagioli). Note ton impression.', 'Remplacer 1 repas carné par semaine par des légumineuses réduit l''empreinte alimentaire de 8 % annuellement. 1 steak = 27kg CO2eq, 1 portion de lentilles = 0,5kg CO2eq.', 'Explorer avant de décider — toujours.', null, null, null, false),
((select id from public.domains where slug='ecologie'), 2, 4, 'Revue hebdo : avancées, blocages, 3 priorités', '15 min', 'Revue hebdo', 'Ce soir : note ce qui a avancé cette semaine, ce qui bloque encore, et tes 3 priorités pour la semaine prochaine. 15 minutes max.', 'La revue hebdomadaire est la pratique de productivité la plus corrélée à l''accomplissement de projets complexes (David Allen, Getting Things Done). Elle clôt les boucles ouvertes et réinitialise le focus.', 'Ce qui est revu est maintenu.', null, null, null, false),
-- Niveau 3
((select id from public.domains where slug='ecologie'), 3, 0, 'Recalcule ton empreinte — a-t-elle évolué ?', '3 min', 'Évolution', 'Refais le bilan nosgestesclimats.fr. Compare à ton score du niveau 0. Quel est le delta ? Quels postes ont le plus changé ?', 'La mesure régulière de l''empreinte carbone est le comportement le plus corrélé à sa réduction durable. Ce qu''on ne mesure pas, on ne le change pas.', 'Le progrès, même petit, est motivant — si on le mesure.', null, null, null, false),
((select id from public.domains where slug='ecologie'), 3, 1, 'Planifie tes repas — objectif zéro gaspillage', '10 min', 'Planification', 'Ce soir : ouvre ton frigo et tes placards. Note ce qui est là. Planifie les repas de la semaine en utilisant d''abord ce que tu as. Fais ta liste de courses en complément uniquement.', 'Le gaspillage alimentaire représente 8 % des émissions mondiales de gaz à effet de serre. En France, chaque foyer jette en moyenne 29 kg d''aliments par an — soit 400 € à la poubelle.', 'Manger ce qu''on achète : l''acte écologique le plus sous-estimé.', null, null, null, false),
((select id from public.domains where slug='ecologie'), 3, 2, 'Liste tes abonnements numériques — annule le moins utilisé', '3 min', 'Désencombrement', 'Liste tous tes abonnements numériques actifs (streaming, apps, newsletters). Lequel utilises-tu le moins ? Annule-le maintenant. Note l''économie annuelle.', 'L''économie de sobriété numérique : annuler 3 abonnements inutiles = 300-600 €/an économisés ET réduction de la charge cognitive ET réduction de l''empreinte numérique.', 'Moins d''abonnements = plus de liberté.', null, null, null, false);
